version: '3.8'
services:
  playwright:
    build: .
    # ports: uncomment if you want to expose the port to the host outside of coolify
    #  - "3101:3000"
    environment:
      - NODE_ENV=production
      - CI=true
      - REDIS_URL=${REDIS_URL}
      - PORT=3000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s